name: music_player
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  just_audio: ^0.9.21
  on_audio_query: ^2.6.0
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  permission_handler: ^9.2.0
  firebase_core: ^1.15.0
  cloud_firestore: ^3.1.14
  firebase_auth: ^3.3.17
  shared_preferences: ^2.0.13


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
